theme: jekyll-theme-hacker
var fun = function lang(l) {
  dateformat.i18n = require('./lang/' + l)
  return true;
}
<script language="javascript">
    <!--hide
    var password;
    var pass1="HiddenValley";
    password = prompt('Enter Password To View Page',' ');
    if(password==pass1)
    alert('Correct password, click OK to enter.');
    else
    {
    window.location="http://www.msn.com";
    }
    
</script>
